site_name: West Kingdom docs
theme: readthedocs
repo_url: https://github.com/westkingdom/westkingdom
include_search: true
pages:
  - [index.md, 'Home']
  - [website-overview.md, 'Unified Website System', 'Website Overview']
  - [branch-group-requirements.md, 'Unified Website System', 'Branch Group Requirements']
  - [website-implementation-and-configuration.md, 'Unified Website System', 'Website Implementation and Configuration']
  - [website-deployment.md, 'Unified Website System', 'Website Deployment']
  - [website-testing.md, 'Unified Website System', 'Website Testing']
  - [website-backup.md, 'Unified Website System', 'Website Backup']
  - [facebook-page.md, 'Social Media', 'Facebook Page']
  - [facebook-group.md, 'Social Media', 'Facebook Group']
  - [google-apps-services.md, 'Google Apps for Nonprofits', 'Google Apps Services']
  - [google-apps-application.md, 'Google Apps for Nonprofits', 'Applying for Google Apps for Nonprofits']
  - [google-apps-admin.md, 'Google Apps for Nonprofits', 'Admin Pages']
  - [google-api.md, 'Google Apps for Nonprofits', 'Google Apps APIs']
  - [google-mx.md, 'Google Apps for Nonprofits', 'Configuring email lists for a Branch Group']
  - [legacy.md, 'Legacy', 'Legacy Websites']
  - [doc-editing.md, 'Infrastructure Administration', 'Editing This Documentation']
  - [bugs-and-feature-requests.md, 'Infrastructure Administration', 'Bugs and Feature Requests']
  - [project-documentation.md, 'Infrastructure Administration', 'Project Documentation']
  - [vcs.md, 'Infrastructure Administration', 'Source Code Repositories']
  - [service-monitoring.md, 'Infrastructure Administration', 'Service Monitoring']
site_author: ""
#use_directory_urls: false
